### ISSUE TITLE
Window layout is broken on OSX

### ISSUE THREAD

**Issue by dbogdanov** [andrepolischuk/keep#11]
I've installed the OSX package. The layout for the window is broken (buttons on the left-top corner are located incorrectly) and I cannot drag-n-drop the window.

<img width="1077" alt="screen shot 2016-10-25 at 16 23 16" src="https://cloud.githubusercontent.com/assets/409668/19690005/7ebb7238-9acf-11e6-8a2a-8b2197a55c3e.png">

**Comment by andrepolischuk** [comment]
@dbogdanov fixed and published as v0.1.2
