### ISSUE TITLE
Activates high-performance graphics card on macOS

### ISSUE THREAD

**Issue by felixbinder** [andrepolischuk/keep#13]
Keep activates, needlessly, the high performance graphics card on Macs that have it.
<img width="281" alt="screen shot 2017-02-02 at 14 28 37" src="https://cloud.githubusercontent.com/assets/24477285/22551197/1399f974-e954-11e6-8551-682c5b0199b0.png"> Compare to this issue: https://github.com/rsms/fb-mac-messenger/pull/344

**Comment by andrepolischuk** [comment]
Hi, can you send a PR?

**Comment by andrepolischuk** [comment]
I close this. Write to me if you still have questions.
