### ISSUE TITLE
Blank screen after signing in

### ISSUE THREAD

**Issue by eliezerlp** [andrepolischuk/keep#15]
After the password screen as part of the usual Google login process I get a blank screen as shown below:
![Blank screen](https://cloud.githubusercontent.com/assets/73103/24623485/8a58c85a-1876-11e7-9d7f-7e54f2725bdb.png)

Let me know if there are any logs to be had anywhere that can be useful. Numerous restarts (and signing in again each time) along with Refreshes did not help.

**Comment by eliezerlp** [comment]
Here are the only logs I get when running with `--verbose` flag...

```
➜  keep git:(master) npm start --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start', '--verbose' ]
npm info using npm@1.3.10
npm info using node@v0.10.25
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info prestart keep@0.1.4
npm info start keep@0.1.4
npm verb unsafe-perm in lifecycle true

> keep@0.1.4 start /home/eliezerlp/keep
> electron .
```

**Comment by andrepolischuk** [comment]
@eliezerlp what os and what keep version do you use?

**Comment by andrepolischuk** [comment]
I close this. Write to me if you still have questions.
