### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alperkabakci** [andrepolischuk/keep#19]
Hi, while installing i get an error like in these page: https://shrib.com/#YHFseQ6MVu5OF1O3FbPm
and here is the npm-debug.log: https://shrib.com/#8Oh1TuFOi6F1b7xN3ZWm .Thanks for any help.

**Comment by andrepolischuk** [comment]
Hi. 

```sh
> electron@1.6.11 postinstall /home/alper/keep/node_modules/electron
> node install.js

sh: 1: node: not found
```

Are you sure that `node` is available for shell? Try to run `node --version`

**Comment by alperkabakci** [comment]
Thanks it is solved but i have another problem like this page. I have elementary os and program version 0.1.5
 here is the output when i'm trying to make it to start
> npm start

> keep@0.1.5 start /home/alper/keep/keep
> electron .

Gtk-Message: Failed to load module "pantheon-filechooser-module"

**Comment by andrepolischuk** [comment]
I found [related issue](https://github.com/electron/electron/issues/2927) in electron repo and same error on [stackexchange](https://elementaryos.stackexchange.com/questions/1859/gtk-message-failed-to-load-module-pantheon-filechooser-module)

**Comment by andrepolischuk** [comment]
I close this. Write to me if you still have questions.
