### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by wlekin** [andrepolischuk/keep#20]
$ sudo nom build:macos
`verbose stack Error: keep@0.1.5 build:macos: 'electron-packager . --overwrite --asar --out=dist --ignore='^/dist$' --platform=darwin --arch=x64 --icon=assets/icon.icns --app-bundle-id=com.andrepolischuk.keep && cd dist/Keep-darwin-x64 && zip -ryXq9 ../Keep-macos-${npm_package_version}.zip Keep.app'
`

**Comment by andrepolischuk** [comment]
@wlekin what error is throwing?

**Comment by dmattox10** [comment]
$ sudo npm build:linux

![screen shot 2017-09-03 at 8 30 47 pm](https://user-images.githubusercontent.com/2966689/30007912-dbfab310-90e6-11e7-9df3-c1d5dd33b25f.png)
![screen shot 2017-09-03 at 8 31 05 pm](https://user-images.githubusercontent.com/2966689/30007911-dbf938e6-90e6-11e7-8a4f-932bdae4e1d9.png)

**Comment by andrepolischuk** [comment]
I bumped packager. You can try pull changes and build again.
