### ISSUE TITLE
Remove Menu in Linux version

### ISSUE THREAD

**Issue by bashpunk** [andrepolischuk/keep#22]
It would be nice to have an option to remove the electron menu in the Linux version of the app - or at least remove it completely for the Linux version. I can't figure out how to do this myself. The OS X version of the app looks like the screenshot in the readme section, without the electron menu.

Thanks for your work!

**Comment by andrepolischuk** [comment]
@bashpunk do you mean remove menu or titlebar? For example on ubuntu menu isn't shown in the application window.

**Comment by bashpunk** [comment]
There*s the electron menubar below the titlebar, see screenshot
![keepmenu](https://user-images.githubusercontent.com/32354273/31032867-16d113f4-a55e-11e7-97df-63ace26a4b2e.png)
 - I'm on Ubuntu Gnome 17.04. I had to install libgconf-2-4 tove found out that when I remove the line "Menu.setApplicationMenu(Menu)" from menu.js the menu disappears.

**Comment by jasiralavi** [comment]
Removing or commenting `Menu.setApplicationMenu(Menu)` works.
But it would be great if it's an option under the 'View' menu. And if you could add a show/hide behaviour while pressing ALT.
