### ISSUE TITLE
Providing executables for releases

### ISSUE THREAD

**Issue by jamzi** [andrepolischuk/keep#37]
Hey Andrey, great work on this app!

One nice thing to have would be real executables that you can install on your OS. Since electron-builder already supports this, we can configure Travis to build and dump files under GitHub releases. What do you think about that?

Example screenshot of another Electron app with provided release executables.
![image](https://user-images.githubusercontent.com/2678290/50659533-3978a200-0f9d-11e9-9518-22a144a80f0a.png)

**Comment by andrepolischuk** [comment]
hi, I added this few month ago, but I have not had time to release. I try do it this week.

**Comment by andrepolischuk** [comment]
@jamzi released in [v0.1.9](https://github.com/andrepolischuk/keep/releases/tag/v0.1.9)
