### ISSUE TITLE
Feature Request: Black Theme

### ISSUE THREAD

**Issue by lukassr** [andrepolischuk/keep#38]
It would be awesome if there was a option to activate a black theme, similar to the chrome extension makes with the Keep webview: [Darkreader](https://darkreader.org/):

<img width="1254" alt="screen shot 2019-01-28 at 1 25 49 pm" src="https://user-images.githubusercontent.com/10482758/51836272-479db200-2300-11e9-9a91-41cf8f1ef04b.png">

Reading the code of Darkreader, the customization have static and dynamic changes, so adding CSS style rules is not enough. I tried to import the extension to Electron and build it, but Electron don't have support for custom extensions yet, and they don't have future plans for it.

Very nice app! It doesn't take a lot of resources like other versions found.

**Comment by lukassr** [comment]
I created a separate app with dark theme: [https://github.com/lukassr/keep-dark-desktop](https://github.com/lukassr/keep-dark-desktop). Used this repo and a dark theme from [https://userstyles.org/](https://userstyles.org/). Thanks for the contribution and the unlicense license.

**Comment by andrepolischuk** [comment]
@lukassr why not pull request?

**Comment by lukassr** [comment]
Since it's my first work with electron, I downloaded the repo to play around, so I know there are bad practices and bad code. Also, it would overwrite the original template, that's why I preferred to have it as a separate repo. 
If I have time to learn how to make a menu with an option to choose the theme, I will send an PR 🙂

**Comment by andrepolischuk** [comment]
it would be great
