### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by lifeofguenter** [andrepolischuk/keep#40]
currently it seems to just be a browser?

![Screenshot from 2019-03-22 21-02-47](https://user-images.githubusercontent.com/241073/54847201-745dbc80-4ce6-11e9-8c4d-3d605e273a64.png)

**Comment by MaverickMartyn** [comment]
What features exactly are you missing?
This **is** essentially just a browser. It's more or less just a way to use it without having to have your fully fledged browser open, with the possibility of adding a few minor features along the way.

**Comment by lifeofguenter** [comment]
@MaverickMartyn there was a misunderstanding then :) - from the screenshot in the README.md I wrongly assumed it would blend into the app nicely, but guessing that is dependent on google :)
