### ISSUE TITLE
Couldn't sign you in

### ISSUE THREAD

**Issue by benderCRC** [andrepolischuk/keep#46]
After entering in my account, I see this...
![goo](https://user-images.githubusercontent.com/51124272/73505286-1129c580-43a0-11ea-9421-fdff7da3ce59.PNG)

I was able to get it to work by copying the files from "AppData/Roaming/Keep/" from a computer that was already signed in, but it has now logged me off and I can not log back in.

**Comment by yebrahim** [comment]
See https://github.com/timche/gmail-desktop/issues/174, seems like the author needs to expose a way to edit the user agent for the workaround to work.

**Comment by benderCRC** [comment]
Hello, I have found how to resolve this issue...

Open the application and click "View" -> "Toggle Developer Tools"

Then select the 3 dots at the very right and click "More tools" -> "Network conditions"

![keep1](https://user-images.githubusercontent.com/51124272/74105104-efaba500-4b28-11ea-859d-2f6652c7b5c1.png)

Next at the very bottom under "User agent" uncheck "Select automatically" and paste in the string:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0`

![keep2](https://user-images.githubusercontent.com/51124272/74105147-3f8a6c00-4b29-11ea-80ff-593f2d1cfeb5.png)

This setting will persist and resolve the issue.

**Comment by vladimirprieto** [comment]
> Hello, I have found how to resolve this issue...
> 
> Open the application and click "View" -> "Toggle Developer Tools"
> 
> Then select the 3 dots at the very right and click "More tools" -> "Network conditions"
> 
> ![keep1](https://user-images.githubusercontent.com/51124272/74105104-efaba500-4b28-11ea-859d-2f6652c7b5c1.png)
> 
> Next at the very bottom under "User agent" uncheck "Select automatically" and paste in the string:
> `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0`
> 
> ![keep2](https://user-images.githubusercontent.com/51124272/74105147-3f8a6c00-4b29-11ea-80ff-593f2d1cfeb5.png)
> 
> This setting will persist and resolve the issue.

not working for me that workaround

**Comment by andrepolischuk** [comment]
fixed in [v0.1.9](https://github.com/andrepolischuk/keep/releases/tag/v0.1.9)
