### ISSUE TITLE
Request: automate the installation progress

### ISSUE THREAD

**Issue by Feichtmeier** [andrepolischuk/keep#9]
Hi there,

awesome project! Could you somehow dump down the installation process a bit?
Though I don't know how far this project has gone! :)
If it is anywhere near ready it would be cool to have some ppa or even a .dev for Ubuntu <3 
Thanks in advance

**Comment by andrepolischuk** [comment]
Hi,
I plan to build packages with release in the week.

**Comment by andrepolischuk** [comment]
@Feichtmeier initial release is out

https://github.com/andrepolischuk/keep/releases/tag/v0.1.0
